project:
  type: website
  output-dir: docs

website:
  title: "Lydia Hefel"
  #favicon: media/initials.png -find good icon
  navbar:
    left:
      - icon: github
        href: https://github.com/lydiahefel
        target: blank
      - href: index.qmd
        text: Home
      - about.qmd
      - resume.qmd
  page-footer:
    left: © Copyright 2024, Lydia Hefel
    right: This website is built with [{{< fa brands r-project title="R Project" >}}](https://www.r-project.org/about.html){target=_blank}
format:
  html:
    theme: 
      light: journal
      dark: cyborg
    css: styles.css
    toc: true

editor: visual